language: elixir

elixir:
  - 1.5.1

otp_release:
  - 20.0

addons:
  postgresql: "9.6"

cache:
  directories:
    - deps

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

before_script:
  - MIX_ENV=test mix do ecto.create, ecto.migrate

script:
  - mix test
  - mix credo

after_script:
  - mix inch.report
